# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_database:
            entity:
                class: AppBundle:User
                property: username
#        in_memory:
#            memory:
#                users:
#                    tndiaye: { password: $2y$07$UOeLbzhKeuv8dBX7CAHtFu3Vbew93ySE0iSiiRhzCEYmyxioea5fi, roles: ROLE_AUTHOR }
#                    admin:   { password: $2y$07$lrnS71wiGBa/y9kFsmRX0OSb3qSn7/9GsvCF7RiXxTnd5H57CqsiW, roles: ROLE_ADMIN }
    encoders:
        AppBundle\Entity\User:
        #Symfony\Component\Security\Core\User\User:
          #plaintext
          algorithm: bcrypt
          cost: 7

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            security: false

        main:
            provider: in_database
            #anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                username_parameter: username
                password_parameter: password
            logout: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login$, roles: ROLE_ANONYNOUS }
        - { path: ^/login_check, roles: ROLE_AUTHENTICATED_FULLY }  
#        - { path: ^/login_check, requires_channel: https, roles: ROLE_AUTHENTICATED_FULLY }